[connections.supabase]
SUPABASE_URL = "https://xkvuovasslzxwuoekgpk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdnVvdmFzc2x6eHd1b2VrZ3BrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDAyMTgyMSwiZXhwIjoyMDg1NTk3ODIxfQ.EkMEYntBYGnUyPAazoqST_6aaXq1Kxs7Pss2dStgIBI"
