[connections.supabase]
SUPABASE_URL = "https://caaaoekepxhlhxsyjuot.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhYWFvZWtlcHhobGh4c3lqdW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNTg5NTksImV4cCI6MjA4NDgzNDk1OX0.lusGBzK7fgewRvlbGjEjeP-6HqF54N1q5D-Lri4Zf4s"
