[connections.supabase]
SUPABASE_URL = "https://xkvuovasslzxwuoekgpk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdnVvdmFzc2x6eHd1b2VrZ3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMjE4MjEsImV4cCI6MjA4NTU5NzgyMX0.0EUFr2ZOw8exiNfUcOmqpe0lN7vwnoqIUzVqNE95Vj8"
